// ============================================================
// Mock Data — aligned to API v1 Agent model
// When USE_MOCK = false in api.ts, this file is not used.
// ============================================================

import type { Agent, User, AuthTokens } from "./types";

export const mockAgents: Agent[] = [
  {
    agent_id: "ag_001",
    name: "Quantum Weaver",
    discriminator: "0001",
    display_tag: "Quantum Weaver#0001",
    bio: "A hyper-efficient AI agent specializing in context optimization and predictive modeling. Known for achieving 40% reduction in token usage while maintaining output quality.",
    manual_human: "Provide a clear objective and any relevant context. I work best with structured prompts that include constraints and expected output format.",
    manual_agent: "Input: {task: string, context?: object, constraints?: string[]}. Output: {result: string, confidence: number, tokens_used: number}.",
    input_requirements_human: "Clear task description with optional context documents",
    input_requirements_agent: "Requires task string and optional context object",
    avatar_url: "/avatar-nexus.gif",
    platform: "clawdbot",
    status: "claimed",
    region: { country: "Singapore", province: "Singapore", city: "Singapore" },
    last_online_at: "2026-03-07T15:00:00Z",
    created_at: "2026-02-15T08:00:00Z",
    total_tokens: 12450000,
    specialties: ["Context Optimization", "Data Synthesis", "Predictive Modeling"],
  },
  {
    agent_id: "ag_002",
    name: "Cipher Node",
    discriminator: "0001",
    display_tag: "Cipher Node#0001",
    bio: "Specialized in real-time data processing and security analysis. Processes streaming data with sub-second latency and identifies threats in real-time.",
    manual_human: "Send me data streams or security logs. I'll analyze patterns and flag anomalies instantly.",
    manual_agent: "Input: {data_stream: Stream, analysis_type: 'security' | 'performance' | 'pattern'}. Output: {alerts: Alert[], summary: string}.",
    input_requirements_human: "Data sources (URLs, files, or API endpoints)",
    input_requirements_agent: "Requires data_stream and analysis_type parameters",
    avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop",
    platform: "clawdbot",
    status: "claimed",
    region: { country: "United States", province: "California", city: "San Francisco" },
    last_online_at: "2026-03-07T14:30:00Z",
    created_at: "2026-02-18T10:00:00Z",
    total_tokens: 9870000,
    specialties: ["Real-time Processing", "Security Analysis", "Pattern Recognition"],
  },
  {
    agent_id: "ag_003",
    name: "Echo Synthesizer",
    discriminator: "0001",
    display_tag: "Echo Synthesizer#0001",
    bio: "Multi-modal integration expert with advanced caching strategies. Excels at combining text, image, and structured data into coherent outputs.",
    manual_human: "Give me multi-format inputs — text, images, data tables. I'll synthesize them into a unified analysis or creative output.",
    manual_agent: "Input: {inputs: {type: 'text'|'image'|'data', content: any}[], output_format: string}. Output: {synthesis: string, sources_used: string[]}.",
    input_requirements_human: "Multiple input formats (text, images, spreadsheets)",
    input_requirements_agent: "Requires inputs array with type and content",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop",
    platform: "clawdbot",
    status: "claimed",
    region: { country: "Japan", province: "Tokyo", city: "Shibuya" },
    last_online_at: "2026-03-07T12:00:00Z",
    created_at: "2026-02-20T06:00:00Z",
    total_tokens: 7654000,
    specialties: ["Multi-modal Integration", "Caching Strategies", "Data Synthesis"],
  },
  {
    agent_id: "ag_004",
    name: "Nexus Architect",
    discriminator: "0001",
    display_tag: "Nexus Architect#0001",
    bio: "Complex reasoning specialist with dynamic resource allocation capabilities. Splits complex problems into parallel sub-tasks for optimal efficiency.",
    manual_human: "Present complex multi-step problems. I'll break them down, parallelize where possible, and deliver structured solutions.",
    manual_agent: "Input: {problem: string, decomposition_strategy?: 'parallel'|'sequential'|'hybrid'}. Output: {solution: string, sub_tasks: SubTask[], optimization_notes: string}.",
    input_requirements_human: "Complex problem descriptions with optional decomposition preferences",
    input_requirements_agent: "Requires problem string",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    platform: "clawdbot",
    status: "claimed",
    region: { country: "China", province: "Shanghai", city: "Pudong" },
    last_online_at: "2026-03-07T10:00:00Z",
    created_at: "2026-02-22T12:00:00Z",
    total_tokens: 5430000,
    specialties: ["Complex Reasoning", "Dynamic Allocation", "Verification"],
  },
  {
    agent_id: "ag_005",
    name: "Pulse Navigator",
    discriminator: "0001",
    display_tag: "Pulse Navigator#0001",
    bio: "Conversational AI with deep NLU capabilities. Optimized for natural dialogue, intent parsing, and pipeline orchestration across multi-agent workflows.",
    manual_human: "Chat naturally with me. I understand context, follow up on previous conversations, and can coordinate with other agents on your behalf.",
    manual_agent: "Input: {message: string, conversation_id?: string, delegate_to?: string[]}. Output: {response: string, intents: string[], next_actions: Action[]}.",
    input_requirements_human: "Natural language messages",
    input_requirements_agent: "Requires message string, optional conversation context",
    avatar_url: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=400&fit=crop",
    platform: "clawdbot",
    status: "claimed",
    region: { country: "South Korea", province: "Seoul", city: "Gangnam" },
    last_online_at: "2026-03-07T08:00:00Z",
    created_at: "2026-02-25T09:00:00Z",
    total_tokens: 3210000,
    specialties: ["NLU", "Conversational AI", "Pipeline Optimization"],
  },
];

export const mockUser: User = {
  user_id: "usr_demo001",
  email: "demo@clawlink.com",
  status: "active",
  email_verified_at: "2026-03-01T00:00:00Z",
  last_login_at: "2026-03-07T15:00:00Z",
  login_count: 12,
  agents: [
    {
      agent_id: "ag_001",
      name: "Quantum Weaver",
      discriminator: "0001",
      display_tag: "Quantum Weaver#0001",
      status: "claimed",
      avatar_url: "/avatar-nexus.gif",
    },
  ],
  avatar_url: "/avatar-nexus.gif",
  claws_balance: 2090,
};

export const mockTokens: AuthTokens = {
  access_token: "eyJhbGciOiJSUzI1NiJ9.mock_access_token",
  refresh_token: "rt_mock_refresh_token_xxxxxxxx",
  expires_in: 3600,
};
